version: "3.9"

services:

  leader:
    container_name: edgar-leader  # defined DNS for the container
    build:
      context: ../../..
      dockerfile: ./.ci/docker/edgar/Dockerfile
    command: /opt/managed.sh leader
    #command: sleep infinity
    volumes:
      - ../../../target/ci/distribution/x86_64-unknown-linux-gnu/:/opt/artifacts
      - "../../../resources/development/tls/insecure-development-ca.pem:/etc/opendut/tls/ca.pem:ro"
      - "../../../resources/development/tls/insecure-development-ca.pem:/usr/local/share/ca-certificates/opendut-ca.crt:ro"
      - "../../../target/debug/:/usr/local/opendut/bin/debug/"
    cap_add:
      - NET_ADMIN
    environment:
      # CLEO
      - OPENDUT_CLEO_NETWORK_CARL_HOST=carl
      - OPENDUT_CLEO_NETWORK_CARL_PORT=443
      - OPENDUT_CLEO_NETWORK_TLS_DOMAIN_NAME_OVERRIDE=carl  # default developer certificate is only valid for localhost
      - OPENDUT_CLEO_NETWORK_OIDC_ENABLED=true
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ID=opendut-cleo-client
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SECRET=$(uuidgen)
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ISSUER_URL=https://keycloak.internal/realms/opendut/
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SCOPES=

      # EDGAR
      - OPENDUT_EDGAR_NETWORK_CARL_HOST=carl
      - OPENDUT_EDGAR_NETWORK_CARL_PORT=443
      - OPENDUT_EDGAR_NETWORK_TLS_DOMAIN_NAME_OVERRIDE=carl  # default developer certificate is only valid for localhost
      - OPENDUT_EDGAR_NETWORK_OIDC_ENABLED=true
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ID=opendut-edgar-client
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SECRET=$(uuidgen)
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ISSUER_URL=https://keycloak.internal/realms/opendut/
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_EDGAR_OPENTELEMETRY_ENABLED=true
      - OPENDUT_EDGAR_OPENTELEMETRY_COLLECTOR_ENDPOINT=http://otel-collector:4317

      # testenv
      - NETBIRD_GROUP=testenv  # only used by unmanaged mode
      - OPENDUT_EDGAR_REPLICAS
      - OPENDUT_EDGAR_SERVICE_USER=root
      - OPENDUT_EDGAR_CLUSTER_NAME
      # dynamically provided
      - NETBIRD_API_TOKEN  # only used by unmanaged mode
      - NETBIRD_MANAGEMENT_API=https://netbird-management
      - OPENDUT_CUSTOM_CA1
      - OPENDUT_CUSTOM_CA2
      - OPENDUT_HOSTS
      # Rust backtrace
      - RUST_BACKTRACE=1

    networks:
      - opendutnet
    privileged: true 

  peer:
    build:
      context: ../../..
      dockerfile: ./.ci/docker/edgar/Dockerfile
    command: /opt/managed.sh
    #command: sleep infinity
    volumes:
      - ../../../target/ci/distribution/x86_64-unknown-linux-gnu/:/opt/artifacts:ro
      - "../../../resources/development/tls/insecure-development-ca.pem:/etc/opendut/tls/ca.pem:ro"
      - "../../../resources/development/tls/insecure-development-ca.pem:/usr/local/share/ca-certificates/opendut-ca.crt:ro"
      - "../../../target/debug/:/usr/local/opendut/bin/debug/:ro"
    cap_add:
      - NET_ADMIN
    environment:
      # CLEO
      - OPENDUT_CLEO_NETWORK_CARL_HOST=carl
      - OPENDUT_CLEO_NETWORK_CARL_PORT=443
      - OPENDUT_CLEO_NETWORK_TLS_DOMAIN_NAME_OVERRIDE=carl  # default developer certificate is only valid for localhost
      - OPENDUT_CLEO_NETWORK_OIDC_ENABLED=true
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ID=opendut-cleo-client
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SECRET=$(uuidgen)
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ISSUER_URL=https://keycloak.internal/realms/opendut/
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SCOPES=

      # EDGAR
      - OPENDUT_EDGAR_NETWORK_CARL_HOST=carl
      - OPENDUT_EDGAR_NETWORK_CARL_PORT=443
      - OPENDUT_EDGAR_NETWORK_TLS_DOMAIN_NAME_OVERRIDE=carl  # default developer certificate is only valid for localhost
      - OPENDUT_EDGAR_NETWORK_OIDC_ENABLED=true
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ID=opendut-edgar-client
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SECRET=$(uuidgen)
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ISSUER_URL=https://keycloak.internal/realms/opendut/
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_EDGAR_OPENTELEMETRY_ENABLED=true
      - OPENDUT_EDGAR_OPENTELEMETRY_COLLECTOR_ENDPOINT=http://otel-collector:4317

      # testenv
      - NETBIRD_GROUP=testenv  # only used by unmanaged mode
      - OPENDUT_EDGAR_REPLICAS
      - OPENDUT_EDGAR_SERVICE_USER=root
      - OPENDUT_EDGAR_CLUSTER_NAME
      # dynamically provided
      - NETBIRD_SETUP_KEY
      - NETBIRD_API_TOKEN  # only used by unmanaged mode
      - NETBIRD_MANAGEMENT_API=https://netbird-management
      - OPENDUT_CUSTOM_CA1
      - OPENDUT_CUSTOM_CA2
      - OPENDUT_HOSTS
      # Rust backtrace
      - RUST_BACKTRACE=1

    deploy:
      mode: replicated
      # edgar replica count (e.g. 3)
      replicas: ${OPENDUT_EDGAR_REPLICAS}
    networks:
      - opendutnet

networks:
  opendutnet:
    name: opendut_network
    external: true  # Use a pre-existing network
